apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sass-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sass-operator
    spec:
      containers:
      - name: sass-operator
        image: sass-infrastructure/operator
        imagePullPolicy: "IfNotPresent"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
